development:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: oncehub-portal_dev

test:
  adapter: async

production:
  adapter: async
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: oncehub-portal_production
